apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
data:
  .env: |-
   {{ range $key, $value := .Values.env }}
   {{ $key }}={{ $value | quote }}
   {{- end -}}