apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  rules:
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
          - backend:
              serviceName: "{{ include "chart.fullname" . }}"
              servicePort: {{.Values.service.port}}
            path: /
    - host: "{{ .Values.ingress.host2 }}"
      http:
        paths:
          - backend:
              serviceName: "{{ include "chart.fullname" . }}"
              servicePort: {{.Values.service.port}}
            path: /

  tls:
    - hosts:
        - "{{ .Values.ingress.host }}"
        - "{{ .Values.ingress.host2 }}"
      secretName: "{{ .Values.ingress.host }}"
