apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  rules:
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
          - backend:
              service:
                name: "{{ include "chart.fullname" . }}"
                port:
                  number: {{.Values.service.port}}
            path: /
            pathType: ImplementationSpecific
    - host: "{{ .Values.ingress.host2 }}"
      http:
        paths:
          - backend:
              service:
                name: "{{ include "chart.fullname" . }}"
                port:
                 number: {{.Values.service.port}}
            path: /
            pathType: ImplementationSpecific
    - host: "{{ .Values.ingress.host3 }}"
      http:
        paths:
          - backend:
              service:
                name: " {{ include "chart.fullname" . }}"
                port:
                 number: {{.Values.service.port}}
            path: /
            pathType: ImplementationSpecific

  tls:
    - hosts:
        - "{{ .Values.ingress.host }}"
        - "{{ .Values.ingress.host2 }}"
        - "{{ .Values.ingress.host3 }}"
      secretName: "{{ .Values.ingress.host }}"
