name: docker

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
        
      - name: Version
        uses: pCYSl5EDgo/cat@master
        id: version
        with:
          path: VERSION
        
      - name: Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        env:
          USERNAME: ${{ secrets.DOCKER_HUB_USER }}
          PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          IMAGE_NAME: "minterteam/explorer-api"
          VERSION: "${{ steps.version.outputs.text }}"
          TAG_NAME: "v${{ steps.version.outputs.text }}"
          DOCKER_BUILD_ARGS: --build-arg VERSION=${{ steps.version.outputs.text }}
