name: MainNet

on:
  push:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 5

      - name: Version
        uses: pCYSl5EDgo/cat@master
        id: version
        with:
          path: VERSION

      - name: Build & Push to Docker Hub
        uses: opspresso/action-docker@v0.2.13
        env:
          USERNAME: ${{ secrets.DOCKER_HUB_USER }}
          PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          IMAGE_NAME: "minterteam/explorer-api"
          LATEST: "true"
          VERSION: "${{ steps.version.outputs.text }}"
          TAG_NAME: ${{ github.sha }}
          DOCKER_BUILD_ARGS: --build-arg VERSION=${{ steps.version.outputs.text }}

      - name: DigitalOcean Kubernetes
        uses: matootie/dokube@master
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
          clusterName: k8s-prod-do

      - name: Install helm
        run: wget https://get.helm.sh/helm-v3.3.4-linux-amd64.tar.gz &> /dev/null && tar xvzf helm-v3.3.4-linux-amd64.tar.gz && chmod 777 linux-amd64/helm && ./linux-amd64/helm ls -n mainnet-reserved

      - name: Deploy to DO
        env:
          TAG_NAME: ${{ github.sha }}
        run: ./linux-amd64/helm upgrade -n mainnet-reserved -i api helm/ --atomic --timeout 100s --set image.tag=$TAG_NAME --reuse-values

      - name: deploy to production cluster
        uses: wahyd4/kubectl-helm-action@v0.1.2
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_PROD_CONFIG_DATA }}
          TAG_NAME: ${{ github.sha }}
        with:
          args: helm upgrade -n mainnet -i api helm/ --atomic --timeout 100s --reuse-values --set image.tag=$TAG_NAME

      - name: notification
        if: cancelled() == false
        uses: xinthink/action-telegram@v1.1
        with:
          botToken: ${{ secrets.TELEGRAM_CI_TOKEN }}
          chatId: ${{ secrets.TELEGRAM_CI_PROD_TO }}
          jobStatus: ${{ job.status }}
          skipSuccess: false
